# Generated by Django 5.2.6 on 2025-09-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('document', models.FileField(upload_to='achievements/')),
                ('category', models.CharField(choices=[('publication', 'Publication'), ('project', 'Project'), ('award', 'Award'), ('certification', 'Certification'), ('other', 'Other')], default='other', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
