# Generated by Django 5.2.6 on 2025-09-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subject_achievement_faculty_achievement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='verified',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='completed_on',
            field=models.DateField(auto_now=True),
        ),
    ]
