# Generated by Django 5.2.6 on 2025-09-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_achievement_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='subject',
        ),
        migrations.AddField(
            model_name='academic',
            name='Subject',
            field=models.ManyToManyField(to='home.subject'),
        ),
    ]
