# Generated by Django 5.2.6 on 2025-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_academic_subject_academic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='Subject',
            field=models.ManyToManyField(related_name='subjects', to='home.subject'),
        ),
    ]
